service:
  name: "desafioigniteserverless"

plugins:
 - serverless-offline
 - serverless-webpack

custom: 
  webpack:
    weppackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws

functions:
  hello:
    handler: src/functions/hello.handle
    events: 
      - http:
          path: /hello
          method: GET
          cors: true