service:
  name: "desafioigniteserverless"

plugins:
 - serverless-offline
 - serverless-webpack
 - serverless-dynamodb-local

custom: 
  webpack:
    weppackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws

functions:
  createTodo:
    handler: src/functions/createTodo.handle
    events: 
      - http:
          path: /createTodo/{userid}
          method: POST
          cors: true
  getUserTodo:
    handler: src/functions/getUserTodo.handle
    events: 
      - http:
          path: /getUserTodo/{userid}
          method: GET
          cors: true

resources:
  Resources:
    dbTodos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5